// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.qinshou.im.protobuf;

public final class MessageProtobuf {
  private MessageProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 对应 java int 类型
     * </pre>
     *
     * <code>int32 cid = 1;</code>
     */
    int getCid();

    /**
     * <pre>
     * 对应 java string 类型
     * </pre>
     *
     * <code>string sid = 2;</code>
     */
    String getSid();
    /**
     * <pre>
     * 对应 java string 类型
     * </pre>
     *
     * <code>string sid = 2;</code>
     */
    com.google.protobuf.ByteString
        getSidBytes();

    /**
     * <code>string fromUserId = 3;</code>
     */
    String getFromUserId();
    /**
     * <code>string fromUserId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromUserIdBytes();

    /**
     * <code>string toUserId = 4;</code>
     */
    String getToUserId();
    /**
     * <code>string toUserId = 4;</code>
     */
    com.google.protobuf.ByteString
        getToUserIdBytes();

    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>int32 type = 5;</code>
     */
    int getType();

    /**
     * <code>int32 contentType = 6;</code>
     */
    int getContentType();

    /**
     * <code>string content = 7;</code>
     */
    String getContent();
    /**
     * <code>string content = 7;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 对应 java long 类型
     * </pre>
     *
     * <code>sint64 sendTimestamp = 8;</code>
     */
    long getSendTimestamp();

    /**
     * <code>sint64 receiveTimestamp = 9;</code>
     */
    long getReceiveTimestamp();

    /**
     * <code>int32 status = 10;</code>
     */
    int getStatus();

    /**
     * <code>string extend = 11;</code>
     */
    String getExtend();
    /**
     * <code>string extend = 11;</code>
     */
    com.google.protobuf.ByteString
        getExtendBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      sid_ = "";
      fromUserId_ = "";
      toUserId_ = "";
      content_ = "";
      extend_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cid_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              sid_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              fromUserId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              toUserId_ = s;
              break;
            }
            case 40: {

              type_ = input.readInt32();
              break;
            }
            case 48: {

              contentType_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 64: {

              sendTimestamp_ = input.readSInt64();
              break;
            }
            case 72: {

              receiveTimestamp_ = input.readSInt64();
              break;
            }
            case 80: {

              status_ = input.readInt32();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              extend_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtobuf.internal_static_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtobuf.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static final int CID_FIELD_NUMBER = 1;
    private int cid_;
    /**
     * <pre>
     * 对应 java int 类型
     * </pre>
     *
     * <code>int32 cid = 1;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int SID_FIELD_NUMBER = 2;
    private volatile Object sid_;
    /**
     * <pre>
     * 对应 java string 类型
     * </pre>
     *
     * <code>string sid = 2;</code>
     */
    public String getSid() {
      Object ref = sid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 对应 java string 类型
     * </pre>
     *
     * <code>string sid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSidBytes() {
      Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUSERID_FIELD_NUMBER = 3;
    private volatile Object fromUserId_;
    /**
     * <code>string fromUserId = 3;</code>
     */
    public String getFromUserId() {
      Object ref = fromUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromUserId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      Object ref = fromUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUSERID_FIELD_NUMBER = 4;
    private volatile Object toUserId_;
    /**
     * <code>string toUserId = 4;</code>
     */
    public String getToUserId() {
      Object ref = toUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string toUserId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      Object ref = toUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <pre>
     * enum
     * </pre>
     *
     * <code>int32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 6;
    private int contentType_;
    /**
     * <code>int32 contentType = 6;</code>
     */
    public int getContentType() {
      return contentType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private volatile Object content_;
    /**
     * <code>string content = 7;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 7;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIMESTAMP_FIELD_NUMBER = 8;
    private long sendTimestamp_;
    /**
     * <pre>
     * 对应 java long 类型
     * </pre>
     *
     * <code>sint64 sendTimestamp = 8;</code>
     */
    public long getSendTimestamp() {
      return sendTimestamp_;
    }

    public static final int RECEIVETIMESTAMP_FIELD_NUMBER = 9;
    private long receiveTimestamp_;
    /**
     * <code>sint64 receiveTimestamp = 9;</code>
     */
    public long getReceiveTimestamp() {
      return receiveTimestamp_;
    }

    public static final int STATUS_FIELD_NUMBER = 10;
    private int status_;
    /**
     * <code>int32 status = 10;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int EXTEND_FIELD_NUMBER = 11;
    private volatile Object extend_;
    /**
     * <code>string extend = 11;</code>
     */
    public String getExtend() {
      Object ref = extend_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extend_ = s;
        return s;
      }
    }
    /**
     * <code>string extend = 11;</code>
     */
    public com.google.protobuf.ByteString
        getExtendBytes() {
      Object ref = extend_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cid_ != 0) {
        output.writeInt32(1, cid_);
      }
      if (!getSidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sid_);
      }
      if (!getFromUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromUserId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toUserId_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      if (contentType_ != 0) {
        output.writeInt32(6, contentType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (sendTimestamp_ != 0L) {
        output.writeSInt64(8, sendTimestamp_);
      }
      if (receiveTimestamp_ != 0L) {
        output.writeSInt64(9, receiveTimestamp_);
      }
      if (status_ != 0) {
        output.writeInt32(10, status_);
      }
      if (!getExtendBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, extend_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cid_);
      }
      if (!getSidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sid_);
      }
      if (!getFromUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromUserId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toUserId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (contentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, contentType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (sendTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, sendTimestamp_);
      }
      if (receiveTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(9, receiveTimestamp_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, status_);
      }
      if (!getExtendBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, extend_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (getCid()
          != other.getCid()) return false;
      if (!getSid()
          .equals(other.getSid())) return false;
      if (!getFromUserId()
          .equals(other.getFromUserId())) return false;
      if (!getToUserId()
          .equals(other.getToUserId())) return false;
      if (getType()
          != other.getType()) return false;
      if (getContentType()
          != other.getContentType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getSendTimestamp()
          != other.getSendTimestamp()) return false;
      if (getReceiveTimestamp()
          != other.getReceiveTimestamp()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getExtend()
          .equals(other.getExtend())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId().hashCode();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTimestamp());
      hash = (37 * hash) + RECEIVETIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveTimestamp());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + EXTEND_FIELD_NUMBER;
      hash = (53 * hash) + getExtend().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtobuf.internal_static_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtobuf.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using com.qinshou.im.protobuf.MessageProtobuf.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        cid_ = 0;

        sid_ = "";

        fromUserId_ = "";

        toUserId_ = "";

        type_ = 0;

        contentType_ = 0;

        content_ = "";

        sendTimestamp_ = 0L;

        receiveTimestamp_ = 0L;

        status_ = 0;

        extend_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtobuf.internal_static_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.cid_ = cid_;
        result.sid_ = sid_;
        result.fromUserId_ = fromUserId_;
        result.toUserId_ = toUserId_;
        result.type_ = type_;
        result.contentType_ = contentType_;
        result.content_ = content_;
        result.sendTimestamp_ = sendTimestamp_;
        result.receiveTimestamp_ = receiveTimestamp_;
        result.status_ = status_;
        result.extend_ = extend_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.getCid() != 0) {
          setCid(other.getCid());
        }
        if (!other.getSid().isEmpty()) {
          sid_ = other.sid_;
          onChanged();
        }
        if (!other.getFromUserId().isEmpty()) {
          fromUserId_ = other.fromUserId_;
          onChanged();
        }
        if (!other.getToUserId().isEmpty()) {
          toUserId_ = other.toUserId_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getContentType() != 0) {
          setContentType(other.getContentType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getSendTimestamp() != 0L) {
          setSendTimestamp(other.getSendTimestamp());
        }
        if (other.getReceiveTimestamp() != 0L) {
          setReceiveTimestamp(other.getReceiveTimestamp());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getExtend().isEmpty()) {
          extend_ = other.extend_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cid_ ;
      /**
       * <pre>
       * 对应 java int 类型
       * </pre>
       *
       * <code>int32 cid = 1;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <pre>
       * 对应 java int 类型
       * </pre>
       *
       * <code>int32 cid = 1;</code>
       */
      public Builder setCid(int value) {
        
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应 java int 类型
       * </pre>
       *
       * <code>int32 cid = 1;</code>
       */
      public Builder clearCid() {
        
        cid_ = 0;
        onChanged();
        return this;
      }

      private Object sid_ = "";
      /**
       * <pre>
       * 对应 java string 类型
       * </pre>
       *
       * <code>string sid = 2;</code>
       */
      public String getSid() {
        Object ref = sid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 对应 java string 类型
       * </pre>
       *
       * <code>string sid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSidBytes() {
        Object ref = sid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 对应 java string 类型
       * </pre>
       *
       * <code>string sid = 2;</code>
       */
      public Builder setSid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应 java string 类型
       * </pre>
       *
       * <code>string sid = 2;</code>
       */
      public Builder clearSid() {
        
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应 java string 类型
       * </pre>
       *
       * <code>string sid = 2;</code>
       */
      public Builder setSidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sid_ = value;
        onChanged();
        return this;
      }

      private Object fromUserId_ = "";
      /**
       * <code>string fromUserId = 3;</code>
       */
      public String getFromUserId() {
        Object ref = fromUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fromUserId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromUserIdBytes() {
        Object ref = fromUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromUserId = 3;</code>
       */
      public Builder setFromUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 3;</code>
       */
      public Builder clearFromUserId() {
        
        fromUserId_ = getDefaultInstance().getFromUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 3;</code>
       */
      public Builder setFromUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUserId_ = value;
        onChanged();
        return this;
      }

      private Object toUserId_ = "";
      /**
       * <code>string toUserId = 4;</code>
       */
      public String getToUserId() {
        Object ref = toUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string toUserId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToUserIdBytes() {
        Object ref = toUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toUserId = 4;</code>
       */
      public Builder setToUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 4;</code>
       */
      public Builder clearToUserId() {
        
        toUserId_ = getDefaultInstance().getToUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 4;</code>
       */
      public Builder setToUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUserId_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>int32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>int32 type = 5;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * enum
       * </pre>
       *
       * <code>int32 type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int contentType_ ;
      /**
       * <code>int32 contentType = 6;</code>
       */
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>int32 contentType = 6;</code>
       */
      public Builder setContentType(int value) {
        
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentType = 6;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 7;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long sendTimestamp_ ;
      /**
       * <pre>
       * 对应 java long 类型
       * </pre>
       *
       * <code>sint64 sendTimestamp = 8;</code>
       */
      public long getSendTimestamp() {
        return sendTimestamp_;
      }
      /**
       * <pre>
       * 对应 java long 类型
       * </pre>
       *
       * <code>sint64 sendTimestamp = 8;</code>
       */
      public Builder setSendTimestamp(long value) {
        
        sendTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应 java long 类型
       * </pre>
       *
       * <code>sint64 sendTimestamp = 8;</code>
       */
      public Builder clearSendTimestamp() {
        
        sendTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long receiveTimestamp_ ;
      /**
       * <code>sint64 receiveTimestamp = 9;</code>
       */
      public long getReceiveTimestamp() {
        return receiveTimestamp_;
      }
      /**
       * <code>sint64 receiveTimestamp = 9;</code>
       */
      public Builder setReceiveTimestamp(long value) {
        
        receiveTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 receiveTimestamp = 9;</code>
       */
      public Builder clearReceiveTimestamp() {
        
        receiveTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 10;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 10;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 10;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object extend_ = "";
      /**
       * <code>string extend = 11;</code>
       */
      public String getExtend() {
        Object ref = extend_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extend_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string extend = 11;</code>
       */
      public com.google.protobuf.ByteString
          getExtendBytes() {
        Object ref = extend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extend = 11;</code>
       */
      public Builder setExtend(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extend = 11;</code>
       */
      public Builder clearExtend() {
        
        extend_ = getDefaultInstance().getExtend();
        onChanged();
        return this;
      }
      /**
       * <code>string extend = 11;</code>
       */
      public Builder setExtendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extend_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"\316\001\n\007Message\022\013\n\003cid\030\001 \001(\005" +
      "\022\013\n\003sid\030\002 \001(\t\022\022\n\nfromUserId\030\003 \001(\t\022\020\n\010toU" +
      "serId\030\004 \001(\t\022\014\n\004type\030\005 \001(\005\022\023\n\013contentType" +
      "\030\006 \001(\005\022\017\n\007content\030\007 \001(\t\022\025\n\rsendTimestamp" +
      "\030\010 \001(\022\022\030\n\020receiveTimestamp\030\t \001(\022\022\016\n\006stat" +
      "us\030\n \001(\005\022\016\n\006extend\030\013 \001(\tB*\n\027com.qinshou." +
      "im.protobufB\017MessageProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "Cid", "Sid", "FromUserId", "ToUserId", "Type", "ContentType", "Content", "SendTimestamp", "ReceiveTimestamp", "Status", "Extend", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
